title: Renan Palmeira # Title of your site

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://renanpalmeira.github.io" # the base hostname & protocol for your site

# twitter_username:     renanpalmeira  # Replace this with your Twitter username
github_username:      renanpalmeira
linkedin_username:    renan-p-47671a89

markdown: kramdown
